src/routes/basket.py
# Setting up routes
from flask import (
    Blueprint,
    render_template,
    request,
    flash,
    redirect,
    url_for,
    make_response,
)
import requests

from utils.basket_util import get_basket, get_basket_data_items, set_basket

# request allows us to do profile?name= in browser

# initialise Blueprint
basket = Blueprint("basket", "basket")

# creating / routes

# routing to main basket page


@basket.route("/", methods=["GET"])
def basket_get():
    user_basket = get_basket(request)
    if not user_basket:
        flash("You do not have any items in your basket")
        return redirect(url_for("home.items_get"))

    items, total_price = get_basket_data_items(user_basket)
    return render_template("basket.html", items=items, total_price=total_price)


# adds items to the basket, also prompts user to log in
# if they add an item without being signed in
@basket.route("/update", methods=["POST"])
def add_item():
    data = request.get_json()
    user_basket = get_basket(request)

    item_id = data["itemId"]

    response = requests.get("http://localhost:8080/api/v1/items/" + item_id)
    item = response.json()

    new_quantity = max(min(int(data["quantity"]), item["quantity"]), 1)
    user_basket[item_id] = new_quantity

    res = make_response()
    return set_basket(res, user_basket)


# deleting items from the basket
@basket.route("/delete", methods=["POST"])
def delete_item():
    data = request.get_json()
    user_basket = get_basket(request)
    item_id = data["itemId"]
    del user_basket[item_id]
    res = make_response()
    return set_basket(res, user_basket)

src/routes/checkout.py
import requests
from flask import Blueprint, render_template, request, flash, redirect, url_for

from utils.basket_util import get_basket_data_items, get_basket

checkout = Blueprint("checkout", "checkout")


@checkout.route("/")
def checkout_get():
    token = request.cookies.get("token")

    if token is None:
        flash("Please Log in first", "info")
        return redirect(url_for("login.login_get"))

    user_basket = get_basket(request)
    items, price = get_basket_data_items(user_basket)

    return render_template("checkout.html", items=items, total=price)


@checkout.route("/", methods=["POST"])
def checkout_post():
    token = request.cookies.get("token")
    user_basket = get_basket(request)

    response = requests.post(
        "http://localhost:8080/api/v1/checkout",
        json=user_basket,
        headers={"Authorization": "Bearer " + token},
    )
    if response.status_code == 200:
        flash("You have successfully checked out", "info")
        res = redirect(url_for("home.items_get"))
        res.delete_cookie("basket")
        return res
    else:
        items, price = get_basket_data_items(user_basket)
        return render_template("checkout.html", items=items)

src/routes/login.py
# Setting up routes
from flask import Blueprint, render_template, request, redirect, url_for, make_response

import requests


login = Blueprint("login", "login")


# routing for log in landing page
@login.route("/", methods=["GET"])
def login_get():

    # allows for passing of html to Python, can also pass variables INTO the html
    return render_template("login.html")


# get and post request
@login.route("/session", methods=["GET", "POST"])
def login_session():

    msg = ""

    response = requests.post(
        "http://localhost:8080/api/v1/session",
        json={"email": request.form["email"], "password": request.form["password"]},
    )

    if response.status_code == 200:

        response_header = response.json()
        print(response_header)
        token = response_header["token"]
        res = redirect(url_for("home.items_get"))

        response = requests.get(
            "http://localhost:8080/api/v1/user",
            headers={"Authorization": "Bearer " + token},
        )
        res.set_cookie("token", token, httponly=True, samesite="Strict")

        return res

    elif response.status_code == 401:
        msg = "Incorrect email and/or password, please try again"
        res = make_response(render_template("login.html", msg=msg))
        return res

src/routes/register.py
# Setting up routes
import requests
from flask import (
    Blueprint,
    render_template,
    request,
    redirect,
    url_for,
    make_response,
)

register = Blueprint("register", "register")


# route for loading registering page
@register.route("/")
def register_get():
    return render_template("register.html")


# creates user based on form inputs which are POSTed in JSON format to the server
@register.route("/createuser", methods=["GET", "POST"])
def create_user():
    response = requests.post(
        "http://localhost:8080/api/v1/user",
        json={
            "email": request.form["email"],
            "password": request.form["password"],
            "firstName": request.form["firstName"],
            "lastName": request.form["lastName"],
            "dob": request.form["dob"],
            "addressLine1": request.form["addressLine1"],
            "addressLine2": request.form["addressLine2"],
            "city": request.form["city"],
            "postCode": request.form["postCode"],
        },
    )

    # error message catching based on returned status code
    if response.status_code == 400:
        response_body = response.json()
        msg = ", ".join(response_body.values())
        res = make_response(render_template("register.html", msg=msg))
        return res

    # user will be created and taken to the user area once registered,
    # cookie created and set
    else:
        response_header = response.json()
        print(response_header)
        token = response_header["token"]

        res = redirect(url_for("home.items_get"))
        res.set_cookie("token", token, httponly=True, samesite="Strict")

        return res

src/routes/reset_password.py
from flask import Blueprint, render_template, flash, redirect, url_for

reset_password = Blueprint("reset_password", "reset_password")


@reset_password.route("/", methods=["GET"])
def reset_password_get():
    return render_template("reset-password.html")


@reset_password.route("/", methods=["POST"])
def reset_password_post():
    flash("Sent reset request", "info")
    return redirect(url_for("home.items_get"))

src/routes/userprofile.py
from flask import Blueprint, render_template, request, make_response

import requests

userprofile = Blueprint("userprofile", "userprofile")


# Takes user to profile page, based on if they are an admin or not
@userprofile.route("/", methods=["GET", "POST"])
def userprofile_get():
    # POST and patch for user information change
    if request.method == "POST":
        form_data = request.form
        data = request.form.to_dict()
        for key, val in form_data.items():
            if val == "":
                del data[key]

        token = request.cookies.get("token")

        if "mgt-submit" in form_data:
            data["id"] = form_data.get("id")
            requests.patch(
                "http://localhost:8080/api/v1/admin/users",
                json=data,
                headers={"Authorization": "Bearer " + token},
            )

        if "personal-submit" in form_data:
            requests.patch(
                "http://localhost:8080/api/v1/user",
                json=data,
                headers={"Authorization": "Bearer " + token},
            )

    # loads current user page
    user_dict = load_user_data()

    # loads get request for all users, used later for admin area
    all_users = load_all_users()

    # redirection for admin page or regular user page
    if user_dict["admin"] is True:
        template = "user-profile-admin.html"
        userRes = make_response(
            render_template(template, user=user_dict, allUsers=all_users)
        )
    else:
        template = "user-profile.html"
        userRes = make_response(render_template(template, user=user_dict))

    return userRes


# loads the user information


def load_user_data():
    token = request.cookies.get("token")
    response = requests.get(
        "http://localhost:8080/api/v1/user",
        headers={"Authorization": "Bearer " + token},
    )

    user_dict = response.json()
    return user_dict


# loads the information for all users which is then given to the adminpage


def load_all_users():
    token = request.cookies.get("token")
    response = requests.get(
        "http://localhost:8080/api/v1/admin/users",
        headers={"Authorization": "Bearer " + token},
    )
    return response.json()

src/templates/basket.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='basket.css') }}"
    />
    <title>Admin Page</title>
  </head>
  <body>
    <header class="header d-flex justify-content-center align-items-center">
      {% include 'components/logo-header.html' %}
    </header>

    <div class="container basket__body">
      <div class="row">
        <main class="col-md-8">
          {% include 'components/basket-items.html' %}
        </main>
        <aside class="col-md-4">
          {% include 'components/basket-total.html' %}
        </aside>
      </div>
    </div>
    {% include 'components/footer.html' %}
    <!-- Separate Popper and Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <script src="../static/basket.js"></script>
  </body>
</html>

src/templates/checkout.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static',filename='checkout.css') }}" />
  <title>Checkout</title>
</head>

<body>
  <header class="header d-flex justify-content-center align-items-center">
    {% include 'components/logo-header.html' %}
  </header>
  <div class="container mt-3">
    <div class="row g-3">
      <main class="col-md-6">
        <div class="container-sm section p-4">
          <h4 class="total__title mb-2 pb-2 border-bottom">Order Summary</h4>
          {% for item in items %}
          <div class="d-flex">
            <p>{{ item.name }} x {{ item.selected_quantity }}</p>
            <p class="ms-auto">£{{ "%.2f"|format(item.price * item.selected_quantity) }}</p>
          </div>
          {% endfor %}
          <div class="d-flex pt-3 border-top border-dark">
            <h5>Subtotal</h5>
            <p class="ms-auto">£{{"%.2f"|format(total)}}</p>
          </div>
        </div>
      </main>
      <aside class="col-md-6">
        <div class="container-sm section p-4">
          <div class="row mb-3">
            <label class="form-label col-5" for="start">Delivery Date</label>
            <div class="col-7">
              <input class="form-control" type="date" id="delivery__date" name="delivery__date" value="2022-12-21"
                min="2022-12-21" max="2023-1-31">
            </div>
          </div>
          <div class="row mb-3">
            <label class="form-label col-5" for="delivery time">Delivery Time</label>
            <div class="col-7">
              <select class="form-select" name="delivery time" id="delivery__time">
                <option value="7:00AM-7:30AM">7:00AM-7:30AM</option>
                <option value="7:30AM-8:00AM">7:30AM-8:00AM</option>
                <option value="8:00AM-8:30AM">8:00AM-8:30AM</option>
                <option value="8:30AM-9:00AM">8:30AM-9:00AM</option>
                <option value="9:00AM-9:30AM">9:00AM-9:30AM</option>
                <option value="9:30AM-10:00AM">9:30AM-10:00AM</option>
                <option value="10:00AM-10:30AM">10:00AM-10:30AM</option>
                <option value="10:30AM-11:00AM">10:30AM-11:00AM</option>
                <option value="11:00AM-11:30AM">11:00AM-11:30AM</option>
                <option value="11:30AM-12:00AM">11:30AM-12:00AM</option>
                <option value="12:00AM-12:30AM">12:00AM-12:30AM</option>
                <option value="12:30AM-1:00PM">12:30AM-1:00PM</option>
              </select>
            </div>
          </div>
          <div class="d-flex mb-3">
            <p>Delivery Price</p>
            {% set delivery_price = 5 %}
            <p class="ms-auto">£{{ "%.2f"|format(delivery_price) }}</p>
          </div>
          <div class="d-flex pt-3 border-top border-dark">
            <h5>Total</h5>
            <p class="ms-auto">£{{"%.2f"|format(total + delivery_price)}}</p>
          </div>
          <div class="d-flex justify-content-evenly">
            <form action="/checkout" method="POST">
              <button class="btn btn__main" type="submit">Checkout</button>
            </form>
            <a class="btn btn__main" href="{{url_for('basket.basket_get')}}">Return to Basket</a>
          </div>
        </div>
      </aside>
    </div>
  </div>

  {% include 'components/footer.html' %}
  <!-- Separate Popper and Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
  <script src="../static/index.js"></script>
  <script src="../static/checkoutDate.js"></script>
</body>

</html>

src/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="{{ url_for('static',filename='home.css') }}" />
  <title>Green Basket</title>
</head>

<body>
  {% include 'components/modal.html' %}

  {% include 'components/header.html' %}

  {% include 'components/products-nav.html' %}

  <div class="d-flex justify-content-center">
    <div class="container_items" id="items-container">

      {% include 'components/item-card.html' %}

    </div>
  </div>

  {% include 'components/pagination.html' %}

  {% include 'components/footer.html' %}

  <!-- Separate Popper and Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
  <script src="static/index.js"></script>
  <script src="static/home.js"></script>
  {% include 'components/modal-script.html' %}
</body>

</html>

src/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{{ url_for('static',filename='newsession.css') }}" />
    <title>Green Basket - Log In</title>
</head>
<body>
  {% include 'components/modal.html' %}
  <header class="header d-flex justify-content-center align-items-center">
    {% include 'components/logo-header.html' %}
  </header>
    <main class="container-sm form__container">
      <h1 class="hero__text">Log In Below</h1>
        <form action='/login/session' method ='POST'>
          <p class="text-danger">{{msg}}</p>
          <section class="form-floating mb-3">
            <input
            type="email"
            name="email"
            class="form-control"
            id="email"
            placeholder="name@example.com"
            required />
            <label for="email">Email address</label>
          </section>
          <section class="form-floating mb-3">
            <input
              type="password"
              name="password"
              class="form-control"
              id="password"
              placeholder="Password"
              required />
            <label for="password">Password</label>
            <p class="form-text"><a href="{{url_for('reset_password.reset_password_get')}}">Forgot Password</a></p>
          </section>
          <section class="mb-3">
            <button type="submit" class="btn btn__main">Log In</button>
            <button type="button" class="btn btn__main">
              <a href="{{url_for('home.items_get')}}">Cancel</a>
            </button>
          </section>
          <section class="form__links row">
            <p class="form-text"> <a href="{{url_for('register.register_get')}}">Register Here</a></p>
          </section>
        </form>
    </main>
    {% include 'components/footer.html' %}
          <!-- Separate Popper and Bootstrap JS -->
    <script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"
  ></script>
  {% include 'components/modal-script.html' %}
</body>
</html>

src/templates/page_not_found.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="{{ url_for('static',filename='home.css') }}" />
    <title>404</title>
</head>


<body>
    <div class="d-flex align-items-center justify-content-center vh-100">
        <div class="text-center">
            <h1 class="display-1 fw-bold">404</h1>
            <p class="fs-3"> <span class="text-danger">Opps!</span> Page not found.</p>
            <p class="lead">
                The page you're looking for doesn't exist.
            </p>
            <a href="{{url_for('home.items_get')}}" class="btn btn__main">Go Home</a>
        </div>
    </div>
</body>

<!-- Separate Popper and Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

</html>

src/templates/register.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static',filename='newsession.css') }}"
    />
    <title>Green Basket - Register</title>
  </head>
  <body>
    <header class="header d-flex justify-content-center align-items-center">
      {% include 'components/logo-header.html' %}
    </header>
    <main class="container-sm form__container">
      <h1 class="hero__text">Please Register Below!</h1>
      <form action="/register/createuser" method="post">
        <p class="text-danger">{{msg}}</p>
        <section class="form-floating mb-3">
          <input
            type="email"
            name="email"
            class="form-control"
            id="email"
            placeholder="name@example.com"
          />
          <label for="email">Email address</label>
        </section>
        <section class="form-floating mb-3">
          <input
            type="password"
            name="password"
            class="form-control"
            id="password"
            placeholder="Password"
          />
          <label for="password">Password</label>
        </section>
        <div class="row g-2">
          <div class="col-sm-6">
            <section class="form-floating mb-3">
              <input
                type="text"
                name="firstName"
                class="form-control"
                id="firstName"
                placeholder="First Name"
              />
              <label for="firstName">First Name</label>
            </section>
          </div>
          <div class="col-sm-6">
            <section class="form-floating mb-3">
              <input
                type="text"
                name="lastName"
                class="form-control"
                id="lastName"
                placeholder="Last Name"
              />
              <label for="lastName">Last Name</label>
            </section>
          </div>
        </div>
        <section class="form-floating mb-3">
          <input
            type="date"
            class="form-control dob"
            placeholder="Date of Birth"
            name="dob"
            id="dob"
            required
          />
          <label for="dob">Date of Birth</label>
        </section>
        <section class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Address Line 1"
            name="addressLine1"
            id="addressLine1"
            required
          />
          <label for="addressLine1">Address Line 1</label>
        </section>
        <section class="form-floating mb-3">
          <input
            type="text"
            class="form-control"
            placeholder="Address Line 2"
            name="addressLine2"
            id="addressLine2"
          />
          <label for="addressLine2">Address Line 2</label>
        </section>
        <div class="row g-2">
          <div class="col-sm-6">
            <section class="form-floating mb-3">
              <input
                type="text"
                class="form-control"
                placeholder="City"
                name="city"
                id="city"
                required
              />
              <label for="city">City</label>
            </section>
          </div>
          <div class="col-sm-6">
            <section class="form-floating mb-3">
              <input
                type="text"
                class="form-control"
                placeholder="Post Code"
                name="postCode"
                id="postCode"
                required
              />
              <label for="postCode">Post Code</label>
            </section>
          </div>
        </div>
        <button class="btn btn__main" type="submit">Register</button>
        <button type="button" class="btn btn__main">
          <a href="{{url_for('home.items_get')}}">Cancel</a>
      </form>
    </main>

    {% include 'components/footer.html' %}
    <!-- Separate Popper and Bootstrap JS -->
    <script
      src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
      integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
      integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
      crossorigin="anonymous"
    ></script>
    <script src = "../static/dob.js">
    </script>

  </body>
</html>

src/templates/reset-password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{{ url_for('static',filename='newsession.css') }}" />
    <title>Green Basket - Reset Password</title>
</head>
<body>
  {% include 'components/modal.html' %}
  <header class="header d-flex justify-content-center align-items-center">
    {% include 'components/logo-header.html' %}
  </header>
    <main class="container-sm form__container">
      <h1 class="hero__text">Reset Password Below</h1>
        <form action='/reset_password' method ='POST'>
          <p class="text-danger">{{msg}}</p>
          <section class="form-floating mb-3">
            <input
            type="email"
            name="email"
            class="form-control"
            id="email"
            placeholder="name@example.com"
            required />
            <label for="email">Email address</label>
          </section>
          <section class="mb-3">
            <button type="submit" class="btn btn__main">Send Reset Request</button>
            <button type="button" class="btn btn__main">
              <a href="{{url_for('home.items_get')}}">Cancel</a>
            </button>
          </section>
        </form>
    </main>
    {% include 'components/footer.html' %}
          <!-- Separate Popper and Bootstrap JS -->
    <script
    src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"
  ></script>
  {% include 'components/modal-script.html' %}
</body>
</html>

src/templates/user-profile.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="{{ url_for('static',filename='profile.css') }}" />
  <title>Grocery Profile Page</title>
</head>

<body>
  {% include 'components/modal.html' %}
  <header class="header d-flex justify-content-between align-items-center">
    {% include 'components/logo-header.html' %}
    <div class="d-flex">
      <div class="me-3">
        <h4>My Profile</h4>
        <p>Hello, {{user.firstName}}!</p>
      </div>
      <button class="header__pagelinks__anchor btn align-self-center">
        <a href={{url_for('home.items_get')}}>Return to Home Page</a>
      </button>
      {% include 'components/header-userprofile-signout.html' %}
    </div>
  </header>
  <div class="container">
    <div class="row g-3 users__container">
      <main class="col-md-6">
        {% include "components/user-personal-details.html" %}
      </main>
      <aside class="col-md-6">
        <section class="container section p-4">
          <h2>Previous Orders</h2>
        </section>

      </aside>

    </div>
  </div>

  {% include 'components/footer.html' %}
  <!-- Separate Popper and Bootstrap JS -->
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>
  <script src="../static/dob.js"></script>
</body>

</html>