src/routes/checkout.py
import requests
from flask import Blueprint, render_template, request, flash, redirect, url_for

from utils.basket_util import get_basket_data_items, get_basket

checkout = Blueprint("checkout", "checkout")


@checkout.route("/")
def checkout_get():
    token = request.cookies.get("token")

    if token is None:
        flash("Please Log in first", "info")
        return redirect(url_for("login.login_get"))

    user_basket = get_basket(request)
    items, price = get_basket_data_items(user_basket)

    return render_template("checkout.html", items=items, total=price)


@checkout.route("/", methods=["POST"])
def checkout_post():
    token = request.cookies.get("token")
    user_basket = get_basket(request)

    response = requests.post(
        "http://localhost:8080/api/v1/checkout",
        json=user_basket,
        headers={"Authorization": "Bearer " + token},
    )
    if response.status_code == 200:
        flash("You have successfully checked out", "info")
        res = redirect(url_for("home.items_get"))
        res.delete_cookie("basket")
        return res
    else:
        items, price = get_basket_data_items(user_basket)
        return render_template("checkout.html", items=items)

src/routes/home.py
# Setting up routes
import base64
import json

from flask import Blueprint, render_template, request, make_response, flash
import requests
import math

# request allows us to do profile?name= in browser

# initialise Blueprint
home = Blueprint("home", "home")


# route for main home page, also gets the items from the database
# for rendering onto the home page
@home.route("/", methods=["GET"])
def items_get():
    response = requests.get("http://localhost:8080/api/v1/items")
    categories_res = requests.get("http://localhost:8080/api/v1/categories")

    categories = categories_res.json()
    items = response.json()

    args = request.args

    if args.get("category") is not None:
        items = list(
            filter(
                lambda item: item["category"]["id"] == int(args.get("category")), items
            )
        )

    pages = math.ceil(len(items) / 24)
    start = 0
    end = 24
    length = len(items)

    if args.get("start") is not None:
        start = int(args.get("start"))
    if args.get("end") is not None:
        end = int(args.get("end"))
    if args.get("length") is not None:
        length = int(args.get("length"))

    res = render_template(
        "index.html",
        items=items,
        pages=pages,
        start=start,
        end=end,
        length=length,
        categories=categories,
        selected_category=args.get("category"),
    )
    return res


# routing for add item button to the basket
@home.route("/add", methods=["POST"])
def add_item():
    data = request.get_json()
    # gets the current basket cookie
    basket_cookie = request.cookies.get("basket")
    basket = (
        json.loads(base64.b64decode(basket_cookie.encode("ascii")).decode("ascii"))
        if basket_cookie is not None
        else {}
    )

    item_id = data["itemId"]

    response = requests.get("http://localhost:8080/api/v1/items/" + item_id)
    item = response.json()

    current_quantity = basket[item_id] if basket.get(item_id) is not None else 0
    to_add_quantity = int(data["quantity"])
    total_quantity = max(min(current_quantity + to_add_quantity, item["quantity"]), 1)
    changed = current_quantity != total_quantity
    if not changed:
        flash("No more items available")

    basket[item_id] = total_quantity

    res = make_response()
    # sets the json of the current basket into the cookie,
    # saving the currently added items
    res.set_cookie(
        "basket",
        base64.b64encode(json.dumps(basket).encode("ascii")).decode("ascii"),
        samesite="Strict",
    )
    return res

src/routes/userprofile.py
from flask import Blueprint, render_template, request, make_response

import requests

userprofile = Blueprint("userprofile", "userprofile")


# Takes user to profile page, based on if they are an admin or not
@userprofile.route("/", methods=["GET", "POST"])
def userprofile_get():
    # POST and patch for user information change
    if request.method == "POST":
        form_data = request.form
        data = request.form.to_dict()
        for key, val in form_data.items():
            if val == "":
                del data[key]

        token = request.cookies.get("token")

        if "mgt-submit" in form_data:
            data["id"] = form_data.get("id")
            requests.patch(
                "http://localhost:8080/api/v1/admin/users",
                json=data,
                headers={"Authorization": "Bearer " + token},
            )

        if "personal-submit" in form_data:
            requests.patch(
                "http://localhost:8080/api/v1/user",
                json=data,
                headers={"Authorization": "Bearer " + token},
            )

    # loads current user page
    user_dict = load_user_data()

    # loads get request for all users, used later for admin area
    all_users = load_all_users()

    # redirection for admin page or regular user page
    if user_dict["admin"] is True:
        template = "user-profile-admin.html"
        userRes = make_response(
            render_template(template, user=user_dict, allUsers=all_users)
        )
    else:
        template = "user-profile.html"
        userRes = make_response(render_template(template, user=user_dict))

    return userRes


# loads the user information


def load_user_data():
    token = request.cookies.get("token")
    response = requests.get(
        "http://localhost:8080/api/v1/user",
        headers={"Authorization": "Bearer " + token},
    )

    user_dict = response.json()
    return user_dict


# loads the information for all users which is then given to the adminpage


def load_all_users():
    token = request.cookies.get("token")
    response = requests.get(
        "http://localhost:8080/api/v1/admin/users",
        headers={"Authorization": "Bearer " + token},
    )
    return response.json()

src/templates/components/basket-items.html
{% for item in items %}
<div class="container p-2 basket__product_card">
  <div class="row">
    <div class="col-sm-4 d-flex">
      <div class="basket__product_image"></div>
    </div>
    <div class="col-sm-8">
      <div class="row">
        <div class="col-8 basket__product_title">{{item.name}}</div>
        <div class="col-4">
          £{{ "%.2f"|format(item.price * item.selected_quantity) }}
        </div>
      </div>
      <div class="row mb-1">
        <div class="col">{{item.description}}</div>
      </div>
      <div class="row align-items-center">
        <div class="col-8">
          <form id="item-{{ item.id }}" class="update-item">
            <input
              type="number"
              name="quantity"
              class="basket__product_quantity"
              id="quantity"
              min="1"
              max="{{ item.quantity }}"
              value="{{ item.selected_quantity }}"
            />
            <button class="btn__main btn__round" aria-label="update item">
              Update
            </button>
          </form>
        </div>
        <div class="col-4 ps-0">
          <form id="item-{{ item.id }}" class="delete-item">
            <button class="btn btn__secondary">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endfor %}
<button type="button" class="btn btn__main mb-3">
  <a href="{{url_for('home.items_get')}}">Continue Shopping</a>
</button>

src/templates/components/basket-total.html
{% set delivery = 5 %}
<div class="container-sm basket__product_card total__card">
  <div class="row mb-3 border-bottom border-2">
    <h5 class="total__title">Basket</h5>
  </div>
  <div class="row mb-3">
    <p class="col total__subtotal">Subtotal</p>
    <p class="col total__sub-price">£{{ "%.2f"|format(total_price) }}</p>
  </div>
  <div class="row">
    <a class="btn btn__main btn__checkout" href="{{url_for('checkout.checkout_get')}}">Go to Checkout</a>
  </div>
</div>

src/templates/components/footer.html
<footer class="footer">
  <p class="footer__text-main">Final Multiverse Bootcamp Project</p>
  <p class="footer__text"> <a href="https://github.com/georeeve/group13-frontend">Created by Ana, George, Tyler and Wiki</a></p>
</footer>

src/templates/components/header-session.html
<ul class="header__links__container d-flex align-items-center">
  <li class="header__links__list">
    <a
      class="header__pagelinks__anchor btn"
      href="{{url_for('userprofile.userprofile_get')}}"
      >Profile</a
    >
  </li>
  <li class="header__links__list">
    <form action="/logout" method="post">
      <button class="header__pagelinks__anchor btn" type="submit">
        Sign Out
      </button>
    </form>
  </li>
</ul>

src/templates/components/header-userprofile-signout.html
<ul class="header__links__container d-flex align-items-center">
<li class="header__links__list">
    <form action="/logout" method="post">
      <button class="header__pagelinks__anchor btn" type="submit">
        Sign Out
      </button>
    </form>
  </li>
</ul>

src/templates/components/header.html
<header class="header d-flex justify-content-between align-items-center">
  {% include 'components/logo-header.html' %}

  <ul class="header__links__container d-flex align-items-center">
    <li class="header__links__list position-relative">
      <a class="header__pagelinks__anchor btn" href="basket">Basket <span
          class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger d-none"
          id="basket-quantity">
          0
          <span class="visually-hidden">items in basket</span>
        </span>
        </button></a>
    </li>
  </ul>

  {% if request.cookies.token %}
  <!-- -->
  {% include 'components/header-session.html' %}
  <!--  -->
  {% else %}
  <!--  -->
  {% include 'components/header-nosession.html' %}
  <!--  -->
  {% endif %}
</header>

src/templates/components/item-card.html
{% for item in items %}
{% if loop.index >= start and loop.index < end %} <div class="card_item category-{{item.category.id}} d-flex">
  <div class="product_image"></div>
  <!-- <img class="product_image"> -->
  <form id="item-{{ item.id }}" class="add-item">
    <div class="card-body d-flex flex-column justify-content-between">
      <div>
        <h3><b>{{item.name}}</b></h3>
        <p>{{item.description}}</p>
      </div>
      <div class="card-body__details d-flex justify-content-between align-items-center">
        <p class="card__price">£{{item.price}}</p>
        <div class="input-group">
          <input name="quantity" type="number" class="form-control" aria-label="quantity to add"
            aria-describedby="button-addon2" min="1" max="{{ item.quantity }}" value="1" />
        </div>
        <button class="btn btn__main add-btn" type="submit">Add</button>
      </div>
    </div>
  </form>
  </div>
  {% endif %} {% endfor %}

src/templates/components/logo-header.html
<a class="header__a" href="{{url_for('home.items_get')}}">
  <div class="header__logo__container d-flex">
    <img
      src="{{url_for('static', filename='assets/basket.svg')}}"
      alt="green basket
    logo"
      class="header__logo"
    />
    <h1 class="header__title">Green Basket</h1>
  </div>
</a>

src/templates/components/modal-script.html
{% with messages = get_flashed_messages() %}
    {% if messages %}
        <script src="{{ url_for('static', filename='modal.js') }}"></script>
    {% endif %}
{% endwith %}

src/templates/components/modal.html
<div class="modal fade" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for msg in messages %}
                    <h5 class="modal-title">{{msg}}</h5>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
    </div>
  </div>
</div>

src/templates/components/pagination.html
<nav class="nav d-flex justify-content-center nav__pagination">
  <ul class="pagination">
    <li class="page-item disabled" id="pagination-prev">
      <a class="page-link"
        href="?start={% if start > 24 %}{{start - 24}}{% else %}{{0}}{% endif %}&end={% if end > 48 %}{{end - 24}}{% else %}{{24}}{% endif %}&length={{items|length}}{% if selected_category %}&category={{selected_category}}{% endif %}">Previous</a>
    </li>
    {% for i in range(pages) %}
    <li class="page-item page-num" id="{{i}}">
      <a class="page-link"
        href="?start={{i * 24}}&end={{i * 24 + 24}}&length={{items|length}}{% if selected_category %}&category={{selected_category}}{% endif %}">{{i
        + 1}}</a>
    </li>
    {% endfor%}

    <li class="page-item" id="pagination-next">
      <a class="page-link"
        href="?start={% if start + 24 >= items|length %}{{start}}{% else %}{{start + 24}}{% endif %}&end={% if end > items|length %}{{end}}{% else %}{{end + 24}}{% endif %}&length={{items|length}}{% if selected_category %}&category={{selected_category}}{% endif %}">Next</a>
    </li>
  </ul>
</nav>

src/templates/components/products-nav.html
<nav class="nav nav__secondary d-flex">
  <div class="btn-group">
    <button class="btn btn__main dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Groceries
    </button>
    <ul class="dropdown-menu">
      {% for category in categories %}
      <li><a id='{{category.id}}' class="dropdown-item dropdown-categories"
          href="?category={{category.id}}">{{category.category}}</a></li>
      {% endfor %}
      <li>
        <hr class="dropdown-divider" />
      </li>
      <li><a class="dropdown-item" href="/">All Food</a></li>
    </ul>
</nav>

src/templates/components/user-management-card.html
{% if allUsers %}
{% for user in allUsers %}
<section class="container section">
    <button class="btn btn__main mb-3" type="button" data-bs-toggle="collapse" data-bs-target="#user-{{user.id}}"
        aria-expanded="false" aria-controls="user-{{user.id}}">
        {{user.email}}
    </button>
    <div class="collapse mgt__container" id="user-{{user.id}}">
        <form method="POST">
            <div class="mb-3">
                <label for="id">id</label>
                <input type="hidden" class="form-control" value="{{user.id}}" name="id">
                <input type="text" class="form-control" value="{{user.id}}" disabled>
            </div>
            <div class="mb-3">
                <label for="email">Email</label>
                <input type="email" class="form-control" placeholder="{{user.email}}" name="email">
            </div>
            <div class="mb-3">
                <label for="password">Password</label>
                <div>
                    <button class="btn btn__main p-1 mt-1">Send Reset Request</button>
                </div>
            </div>
            <div class="mb-3">
                <label for="firstName">First Name</label>
                <input type="text" class="form-control" placeholder="{{user.firstName}}" name="firstName">
            </div>
            <div class="mb-3">
                <label for=" lastName">Last Name</label>
                <input type="text" class="form-control" placeholder="{{user.lastName}}" name="lastName">
            </div>
            <div class="mb-3">
                <label for="dob">Date of Birth</label>
                <input type="date" class="form-control dob" placeholder="{{user.dob}}" name="dob">
            </div>
            <div class="mb-3">
                <label for="addressLine1">Address Line 1</label>
                <input type="text" class="form-control" placeholder="{{user.addressLine1}}" name="addressLine1">
            </div>
            <div class="mb-3">
                <label for="addressLine2">Address Line 2</label>
                <input type="text" class="form-control" placeholder="{{user.addressLine2}}" name="addressLine2">
            </div>
            <div class="mb-3">
                <label for="city">City</label>
                <input type="text" class="form-control" placeholder="{{user.city}}" name="city">
            </div>
            <div class="mb-3">
                <label for="postCode">Post Code</label>
                <input type="text" class="form-control" placeholder="{{user.postCode}}" name="postCode">
            </div>
            <div class="mb-2">
                <button class="btn btn__main" name="mgt-submit" type="submit">Update User</button>
            </div>

        </form>
    </div>
</section>
{% endfor %}
{% endif %}

src/templates/components/user-personal-details.html
<section class="container section p-4">
    <h2> Edit Personal Details Below</h2>
    <form method="POST">
        <div class="mb-3">
            <label for="email">Email</label>
            <input type="email" class="form-control" placeholder="{{user.email}}" name="email" id="floatingInput">
        </div>
        <div class="mb-3">
            <label for="password">Password</label>
            <input type="password" class="form-control" placeholder="Enter Password" name="password" id="password">
        </div>
        <div class="mb-3">
            <label for="firstName">First Name</label>
            <input type="text" class="form-control" placeholder="{{user.firstName}}" name="firstName" id="firstName">
        </div>
        <div class="mb-3">
            <label for=" lastName">Last Name</label>
            <input type="text" class="form-control" placeholder="{{user.lastName}}" name="lastName" id="lastName">
        </div>
        <div class="mb-3">
            <label for="dob">Date of Birth</label>
            <input type="date" class="form-control dob" placeholder="{{user.dob}}" name="dob" id="dob">
        </div>
        <div class="mb-3">
            <label for="addressLine1">Address Line 1</label>
            <input type="text" class="form-control" placeholder="{{user.addressLine1}}" name="addressLine1"
                id="addressLine1">
        </div>
        <div class="mb-3">
            <label for="addressLine2">Address Line 2</label>
            <input type="text" class="form-control" placeholder="{{user.addressLine2}}" name="addressLine2"
                id="addressLine2">
        </div>
        <div class="mb-3">
            <label for="city">City</label>
            <input type="text" class="form-control" placeholder="{{user.city}}" name="city" id="city">
        </div>
        <div class="mb-3">
            <label for="postCode">Post Code</label>
            <input type="text" class="form-control" placeholder="{{user.postCode}}" name="postCode" id="postCode">
        </div>
        <div>
            <button class="btn btn__main" name="personal-submit" type="submit">Submit</button>
        </div>
    </form>
</section>